title: Learn, Converse, Share
timezone: America/Chicago
collections:
  posts:
    title: Posts
    permalink: /posts/:title/
    output: true
  uploads:
    title: Uploads
    output: true
description: My Personal Blog
author: Jason Meridth
github: https://github.com/jmeridth
about: I am a continuously learning software developer trying to not let best be the enemy of better.
google_analytics: UA-38456568-3
google_verify: 2LRsgnHFM86Lph9HmYJGK6Uoa-Fn75nSU9YdAGbZAo4
locale: en_US
avatar_url: /static/img/avatar.png

enableTags: true
tagarray: []

social:
    - icon: fa-twitter
      link: "https://twitter.com/jmeridth"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/jmeridth"
    - icon: fa-stack-exchange
      link: "https://stackoverflow.com/users/963931/jmeridth"
    - icon: fa-github
      link: "https://github.com/jmeridth"
    - icon: fa-key
      link: "https://keybase.io/jmeridth/key.asc"
    - icon: fa-file
      link: "http://tinyurl.com/meridthresume"
    - icon: fa-calendar
      link: "https://calendly.com/jmeridth"

share:
  twitter:
    username: jmeridth
    image: /images/meridth_llc_cog.png

urls:
  - text: About Me
    url: /about/
  - text: Tags
    url: /tags/
  - text: Feed
    url: /feed.xml

sass:
  sass_dir: _sass
  style: compressed

url: "https://blog.jasonmeridth.com"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-avatar
  - jekyll-feed
  - jekyll-seo-tag

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']

exclude:
- demo/*
- lib
- config.rb
- Capfile
- config
- Gemfile
- Gemfile.lock
- README.md
- LICENSE
- log
- Rakefile
- Rakefile.rb
- tmp
- less
- "*.sublime-project"
- "*.sublime-workspace"
- test
- spec
- Gruntfile.js
- package.json
- node_modules
- Dockerfile
- docker-compose.yml
